# pubspec.yaml
name: micro_mobility_app
description: EOM START 

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # Используйте последнюю версию
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  flutter_map_geojson: ^1.0.8
  intl: ^0.20.2
  camera: ^0.11.2 # Используйте актуальную версию
  mobile_scanner: ^3.5.1  
  shared_preferences: ^2.2.2 # Для локального хранения данных
  share_plus: ^11.0.0 # Для функции "Поделиться"
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.0  # Для отображения виджета
  http: ^1.1.0           # Для запросов к бэкенду
  dio: ^5.1.0            # Для HTTP-запросов
  flutter_secure_storage: ^9.2.4 # Для безопасного хранения токенов
  webview_flutter_android: ^4.9.0
  webview_flutter_wkwebview: ^3.10.2
  cached_network_image: ^3.3.0
  win32: ^5.14.0
  image: ^4.5.4       # Для сжатия фото



  
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_info_plus: ^8.3.0
  image_picker: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.1.5
  telegram_login_flutter: ^1.0.1
  syncfusion_flutter_charts: ^30.2.4
  file_picker: ^10.3.1
  mocktail: ^1.0.4
  connectivity_plus: ^6.1.5
  lottie: ^3.3.1
  audioplayers: ^6.5.0
  timezone: ^0.10.1
  jwt_decode: ^0.3.1
  web_socket_channel: ^3.0.3
  location: ^8.0.1
  upgrader: ^11.5.0
  battery_plus: ^5.0.0
  # flutter_map_tile_caching: ^10.0.0
  flutter_map_tile_caching: ^9.1.4
  flutter_background_service: ^5.0.0
  sqflite: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/geojson/
    - assets/almaty_zone.geojson
    - assets/icons/
    - assets/icons/Insider-loading.json
    - assets/images/
    - assets/fonts/arial_bolditalicmt.ttf


dev_dependencies:
  rename: ^3.1.0
